name: sample_firebase
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_fonts: ^1.1.1
  percent_indicator: ^2.1.7+2
  flutter_search_bar: ^2.1.0
  firebase_database: ^4.4.0
  flutter_spinkit: ^4.1.2
  syncfusion_flutter_charts: ^18.4.35
  floating_action_bubble: ^1.1.2
  flip_card: ^0.4.4
  carousel_slider: ^3.0.0
  popup_menu: ^1.0.5
  overlay_support: ^1.0.5
  firebase_storage: ^4.0.0
  # firebase_analytics: ^5.0.6
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/drills.png
    - images/stories.png
    - images/dictionary.png
    - images/progress.png
    - images/settings.png
    - images/travel.png
    - images/basic.png
    - images/family.png
    - images/school.png
    - images/shopping.png
    - images/study.png
    - images/locked.png
    - images/lock.png
    - images/like.png
    - images/sad.png
    - images/unlock.png
    - images/unlocked.png
    - images/story1_1.png
    - images/story1_2.png
    - images/story1_3.png
    - images/story1_4.png
    - images/story1_5.png
    - images/school1.png
    - images/school2.png
    - images/school3.png
    - images/school4.png
    - images/school5.png
    - images/school6.png
    - images/school7.png
    - images/school8.png
    - images/shopping1.png
    - images/shopping2.png
    - images/shopping3.png
    - images/shopping4.png
    - images/shopping5.png
    - images/shopping6.png
    - images/shopping7.png
    - images/travel1.png
    - images/travel2.png
    - images/travel3.png
    - images/travel4.png
    # - images/travel5.png
    - images/travel6.png
    - images/travel7.png
    - images/travel8.png
    - images/family1.png
    - images/family2.png
    - images/family3.png
    - images/family4.png
    - images/family5.png
    - images/family6.png
    - images/family7.png
    - images/family8.png
    - images/family9.png
    - images/10words.png
    - images/50words.png
    - images/100words.png
    - images/200words.png
    - images/300words.png
    - images/400words.png
    - images/500words.png
    - images/600words.png
    - images/700words.png
    - images/3days.png
    - images/5days.png
    - images/7days.png
    - images/15days.png
    - images/30days.png
    - images/medal.png
    - images/10xp.png
    - images/100xp.png
    - images/500xp.png
    - images/1000xp.png
    - images/3000xp.png
    - images/5000xp.png
    - images/10000xp.png
    - images/girl.jpg
    - images/boy.jpg
    - images/girl2.jpg
    - images/boy2.jpg
    - images/girl3.jpg
    - images/boy3.jpg
    - images/flash.jpg
    - images/stories_icon.png
    - images/trophies_icon.png
    - images/practice_icon.png
    - images/dictionary_icon.png
    - images/basics_icon.png
    - images/travel_icon.png
    - images/shopping_icon.png
    - images/family_icon.png
    - images/school_icon.png
    - images/background.jpg
    - images/background.gif











    






















  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
